### ISSUE TITLE
Rename branch master to main

### ISSUE THREAD

**Issue by wilsonmar** [thedeo/terraform-aws-trailwatch#4]
See https://github.com/github/renaming
and https://www.git-tower.com/learn/git/faq/git-rename-master-to-main
and https://www.r-bloggers.com/2020/07/5-steps-to-change-github-default-branch-from-master-to-main/

[Step 1 – Move the master branch to ‘main’](https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/#step-1---move-the-master-branch-to-main)
[Step 2 – Push ‘main’ to remote repo](https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/#step-2---push-main-to-remote-repo)
[Step 3 – Point HEAD to ‘main’ branch](https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/#step-3---point-head-to-main-branch)
[Step 4 – Change default branch to ‘main’ on GitHub site](https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/#step-4---change-default-branch-to-main-on-github-site)
[Step 5 – Delete ‘master’ branch on the remote repo](https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/#step-5---delete-master-branch-on-the-remote-repo)

**Comment by thedeo** [comment]
Thanks for the advice on this! I've moved to main branch.
