### ISSUE TITLE
Output to JSON file

### ISSUE THREAD

**Issue by wilsonmar** [thedeo/terraform-aws-trailwatch#5]
The app currently outputs to a tabular CSV file, which enables viewing offline using Excel and custom programs.
It would also be nice to output to JSON as well for those who are more comfortable with that file file format.
But this is a low impact change because utilities are available to convert from CSV to JSON outside this app,
such as https://retool.com/utilities/convert-csv-to-json online.

**Comment by thedeo** [comment]
I've added JSON as a download option on all data tables.
