### ISSUE TITLE
External Hashicorp Vault to store secrets

### ISSUE THREAD

**Issue by wilsonmar** [thedeo/terraform-aws-trailwatch#8]
Currently, secrets needed by this app are stored in a file in the user $HOME folder, away from GitHub.
The template file defining variable names (with sample data) needs to be renamed and copied to a folder away from GitHub. The renamed filename is specified in .gitignore to prevent inadvertent exposure.

However, the file can be lost/stolen if the laptop is lost/stolen or compromised by clicking a malicious phishing website.
Having secrets stored in an external Hashicorp Vault server or cloud instance would enable no-effort recovery after a lost/stolen/damaged laptop. See https://wilsonmar.github.io/github-data-security/#SecretsInCloud

**Comment by thedeo** [comment]
Thank you for bringing this up.

If somebody uses this solution as is, by default it is designed for a user to store variables in terraform.tfvars file. The .gitignore file keeps that file from being synced into github.

The information stored in the terraform.tfvars is easily re-obtainable so there is no risk of loss there if an individual decided to store them locally. If an individual using this project desired to store secrets in something like Terraform Cloud or Vault that is not something that I can automate. I do highly encourage using every measure possible to keep secrets secure however, the storing of terraform secrets would need to be handled by the individual deploying the solution.

I will add some notes to the README providing more explicit direction in regards to this.
